### ISSUE TITLE
watchFile(file) 存在命令执行漏洞，各位搬运的时候请注意

### ISSUE THREAD

**Issue by Jayl1n** [ngtmuzi/webshell-demo#1]
![tim 20181004234418](https://user-images.githubusercontent.com/18259284/46486202-d8232480-c82f-11e8-98ec-8b3a937998b4.png)

**Comment by ngtmuzi** [comment]
本项目仅是一篇[博客文章](https://ngtmuzi.github.io/使用socket-io在页面上输出实时日志/)的示例代码，请勿直接用于自身项目，文章内也有警告这样的webshell是十分危险的，代码仅作示范用途

**Comment by Jayl1n** [comment]
但是还是有程序员部署到线上了 😂

**Comment by ngtmuzi** [comment]
这我确实没想到有人会直接搬过来用于生产环境...我会修改readme加上警告
